name: simplebank-app

services:
  
  db:
    container_name: simplebank-db
    image: postgres:14.11-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 1s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
  
  migrate:
    container_name: simplebank-migrate
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migration:/migration:ro
    command:
      [ "-path", "/migration", "-database", "postgresql://root:root@simplebank-db:5432/simple_bank?sslmode=disable", "-verbose", "up" ]

  api:
    container_name: simplebank-api
    image: simplebank-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:root@simplebank-db:5432/simple_bank?sslmode=disable
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  db-data:
    name: simplebank-db-data
