name: simplebank-app

services:
  db:
    container_name: simplebank-db
    image: postgres:14.11-alpine3.19
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 1s
      retries: 5
  api:
    container_name: simplebank-api
    image: simplebank-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:root@simplebank-db:5432/simple_bank?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
        restart: true
